// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dequeue() {
  return window['go']['incomingEventsQueue']['IncomingEventsQueue']['Dequeue']();
}

export function Enqueue(arg1, arg2) {
  return window['go']['incomingEventsQueue']['IncomingEventsQueue']['Enqueue'](arg1, arg2);
}
