// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {incomingEventsQueue} from '../models';

export function Dequeue():Promise<incomingEventsQueue.event>;

export function Enqueue(arg1:string,arg2:any):Promise<void>;
