// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWorkObject() {
  return window['go']['main']['App']['GetWorkObject']();
}

export function GetWorkObjectPoints() {
  return window['go']['main']['App']['GetWorkObjectPoints']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
