// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {physicalGeometry} from '../models';

export function GetWorkObject():Promise<physicalGeometry.GraphicalMesh>;

export function GetWorkObjectPoints():Promise<physicalGeometry.GraphicalMesh>;

export function Greet(arg1:string):Promise<string>;
